import type { QuestionTemplate } from '@/lib/templates/types';
import { shapeName, sideCount } from './helpers';

/** Year 1 - NSW Stage 1. */
export const year1: QuestionTemplate[] = [
  // ------------------------------------------------------------------
  // Year 1
  //
  // Numbers to 120, partitioning into tens and ones, skip counting, addition
  // and subtraction within 20, equal sharing and grouping, money, informal
  // units of length, and durations in days and hours.
  // ------------------------------------------------------------------
  {
    id: 'maths.1.counting-numbers.skip',
    subject: 'maths',
    topic: 'counting numbers',
    level: '1',
    prompt: 'Counting by {step}s: {x}, {x + step}, {x + 2 * step}, ?',
    vars: [
      { name: 'step', kind: 'pick', from: [2, 5, 10] },
      { name: 'x', kind: 'int', min: 'step', max: 'step * 5' },
    ],
    constraints: ['mod(x, step) == 0'],
    answer: 'x + 3 * step',
    hint: 'Add {step} each time.',
    tags: ['AC9M1A01'],
  },
  {
    id: 'maths.1.counting-numbers.after-100',
    subject: 'maths',
    topic: 'counting numbers',
    level: '1',
    prompt: 'What number comes after {x}?',
    vars: [{ name: 'x', kind: 'int', min: '95', max: '119' }],
    answer: 'x + 1',
    tags: ['AC9M1N01'],
  },
  {
    id: 'maths.1.counting-numbers.largest',
    subject: 'maths',
    topic: 'counting numbers',
    level: '1',
    prompt: 'Which of these is the largest: {a}, {b} or {c}?',
    vars: [
      { name: 'a', kind: 'int', min: '10', max: '120' },
      { name: 'b', kind: 'int', min: '10', max: '120' },
      { name: 'c', kind: 'int', min: '10', max: '120' },
    ],
    constraints: ['a != b', 'b != c', 'a != c'],
    answer: 'max(a, b, c)',
    tags: ['AC9M1N01'],
  },
  {
    id: 'maths.1.counting-numbers.ten-more',
    subject: 'maths',
    topic: 'counting numbers',
    level: '1',
    prompt: 'What is 10 more than {x}?',
    vars: [{ name: 'x', kind: 'int', min: '5', max: '109' }],
    answer: 'x + 10',
    hint: 'Only the tens digit changes.',
    tags: ['AC9M1N01'],
  },
  {
    id: 'maths.1.counting-numbers.ten-less',
    subject: 'maths',
    topic: 'counting numbers',
    level: '1',
    prompt: 'What is 10 less than {x}?',
    vars: [{ name: 'x', kind: 'int', min: '15', max: '120' }],
    answer: 'x - 10',
    tags: ['AC9M1N01'],
  },
  {
    id: 'maths.1.place-value.count-tens',
    subject: 'maths',
    topic: 'place value',
    level: '1',
    prompt: 'How many whole tens are there in {x}?',
    vars: [{ name: 'x', kind: 'int', min: '20', max: '99' }],
    answer: 'floor(x / 10)',
    hint: 'Look at the first digit of {x}.',
    tags: ['AC9M1N02'],
  },
  {
    id: 'maths.1.place-value.count-ones',
    subject: 'maths',
    topic: 'place value',
    level: '1',
    prompt: '{x} is {tens} tens and how many ones?',
    vars: [
      { name: 'x', kind: 'int', min: '21', max: '99' },
      { name: 'tens', kind: 'expr', expr: 'floor(x / 10)' },
    ],
    constraints: ['mod(x, 10) != 0'],
    answer: 'mod(x, 10)',
    tags: ['AC9M1N02'],
  },
  {
    id: 'maths.1.place-value.build',
    subject: 'maths',
    topic: 'place value',
    level: '1',
    prompt: 'What number is {tens} tens and {ones} ones?',
    // From 2, so it never reads "1 tens".
    vars: [
      { name: 'tens', kind: 'int', min: '2', max: '9' },
      { name: 'ones', kind: 'int', min: '2', max: '9' },
    ],
    answer: 'tens * 10 + ones',
    tags: ['AC9M1N02'],
  },
  {
    id: 'maths.1.addition.small',
    subject: 'maths',
    topic: 'addition',
    level: '1',
    prompt: 'What is {x} + {y}?',
    vars: [
      { name: 'x', kind: 'int', min: '1', max: '9' },
      { name: 'y', kind: 'int', min: '1', max: '9' },
    ],
    answer: 'x + y',
    hint: 'Start at {x} and count on {y} more.',
    tags: ['AC9M1N04'],
  },
  {
    id: 'maths.1.addition.story',
    subject: 'maths',
    topic: 'addition',
    level: '1',
    prompt: 'Mia has {x} stickers. She is given {y} more. How many does she have now?',
    vars: [
      { name: 'x', kind: 'int', min: '2', max: '12' },
      { name: 'y', kind: 'int', min: '1', max: '8' },
    ],
    answer: 'x + y',
    tags: ['AC9M1N05'],
  },
  {
    id: 'maths.1.addition.within-twenty',
    subject: 'maths',
    topic: 'addition',
    level: '1',
    prompt: 'What is {x} + {y}?',
    vars: [
      { name: 'x', kind: 'int', min: '6', max: '14' },
      { name: 'y', kind: 'int', min: '3', max: '20 - x' },
    ],
    answer: 'x + y',
    hint: 'Make ten first, then add what is left over.',
    tags: ['AC9M1N04'],
  },
  {
    id: 'maths.1.addition.double',
    subject: 'maths',
    topic: 'addition',
    level: '1',
    prompt: 'What is double {x}?',
    vars: [{ name: 'x', kind: 'int', min: '2', max: '10' }],
    answer: 'x * 2',
    hint: '{x} + {x}',
    tags: ['AC9M1N04'],
  },
  {
    id: 'maths.1.addition.missing-part',
    subject: 'maths',
    topic: 'addition',
    level: '1',
    prompt: 'What goes in the box? {x} + ? = {total}',
    vars: [
      { name: 'x', kind: 'int', min: '2', max: '10' },
      { name: 'rest', kind: 'int', min: '1', max: '10' },
      { name: 'total', kind: 'expr', expr: 'x + rest' },
    ],
    answer: 'rest',
    hint: 'Count on from {x} until you reach {total}.',
    tags: ['AC9M1N04'],
  },
  {
    id: 'maths.1.subtraction.difference',
    subject: 'maths',
    topic: 'subtraction',
    level: '1',
    prompt: 'What is the difference between {x} and {y}?',
    vars: [
      { name: 'x', kind: 'int', min: '5', max: '20' },
      { name: 'y', kind: 'int', min: '1', max: '19' },
    ],
    constraints: ['x > y'],
    answer: 'x - y',
    hint: 'Count back from {x} until you reach {y}.',
    tags: ['AC9M1N04'],
  },
  {
    id: 'maths.1.subtraction.story',
    subject: 'maths',
    topic: 'subtraction',
    level: '1',
    // "{y} of them" rather than "{y} fly away", and y from 2 so the verb agrees.
    prompt: 'There are {x} birds on a wall. {y} of them fly away. How many are left?',
    vars: [
      { name: 'x', kind: 'int', min: '5', max: '20' },
      { name: 'y', kind: 'int', min: '2', max: 'x - 1' },
    ],
    answer: 'x - y',
    tags: ['AC9M1N05'],
  },
  {
    id: 'maths.1.subtraction.within-twenty',
    subject: 'maths',
    topic: 'subtraction',
    level: '1',
    prompt: 'What is {x} − {y}?',
    vars: [
      { name: 'x', kind: 'int', min: '12', max: '20' },
      { name: 'y', kind: 'int', min: '3', max: '9' },
    ],
    answer: 'x - y',
    hint: 'Take away enough to get down to ten first.',
    tags: ['AC9M1N04'],
  },
  {
    id: 'maths.1.sharing.equal-groups',
    subject: 'maths',
    topic: 'sharing',
    level: '1',
    prompt: '{total} pencils are shared equally between {n} friends. How many does each friend get?',
    vars: [
      { name: 'n', kind: 'int', min: '2', max: '5' },
      { name: 'each', kind: 'int', min: '2', max: '6' },
      { name: 'total', kind: 'expr', expr: 'n * each' },
    ],
    answer: 'each',
    tags: ['AC9M1N06'],
  },
  {
    id: 'maths.1.sharing.how-many-groups',
    subject: 'maths',
    topic: 'sharing',
    level: '1',
    prompt: 'How many groups of {n} can you make from {total} counters?',
    vars: [
      { name: 'n', kind: 'int', min: '2', max: '5' },
      { name: 'groups', kind: 'int', min: '2', max: '8' },
      { name: 'total', kind: 'expr', expr: 'n * groups' },
    ],
    answer: 'groups',
    hint: 'Skip count by {n}s until you reach {total}.',
    tags: ['AC9M1N06'],
  },
  {
    id: 'maths.1.money.count-coins',
    subject: 'maths',
    topic: 'money',
    level: '1',
    prompt: 'How many {coin}c coins do you need to make {total}c?',
    vars: [
      { name: 'coin', kind: 'pick', from: [5, 10, 20] },
      { name: 'many', kind: 'int', min: '2', max: '8' },
      { name: 'total', kind: 'expr', expr: 'coin * many' },
    ],
    answer: 'many',
    hint: 'Skip count by {coin}s.',
    tags: ['AC9M1N05'],
  },
  {
    id: 'maths.1.number-patterns.count-back',
    subject: 'maths',
    topic: 'number patterns',
    level: '1',
    prompt: 'What comes next? {x}, {x - step}, {x - 2 * step}, ?',
    vars: [
      { name: 'step', kind: 'pick', from: [2, 5, 10] },
      { name: 'x', kind: 'int', min: 'step * 4', max: 'step * 12' },
    ],
    constraints: ['mod(x, step) == 0'],
    answer: 'x - 3 * step',
    hint: 'The numbers go down by {step} each time.',
    tags: ['AC9M1A01'],
  },
  {
    id: 'maths.1.number-patterns.repeating-unit',
    subject: 'maths',
    topic: 'number patterns',
    level: '1',
    prompt: 'What comes next? {a}, {b}, {c}, {a}, {b}, {c}, {a}, {b}, ?',
    vars: [
      { name: 'a', kind: 'int', min: '1', max: '3' },
      { name: 'b', kind: 'int', min: '4', max: '6' },
      { name: 'c', kind: 'int', min: '7', max: '9' },
    ],
    answer: 'c',
    hint: 'The part that repeats is {a}, {b}, {c}.',
    tags: ['AC9M1A02'],
  },
  {
    id: 'maths.1.measurement.how-much-longer',
    subject: 'maths',
    topic: 'measurement',
    level: '1',
    prompt:
      'A rope is {a} paperclips long. A pencil is {b} paperclips long. How many paperclips longer is the rope?',
    vars: [
      { name: 'a', kind: 'int', min: '8', max: '20' },
      { name: 'b', kind: 'int', min: '2', max: '7' },
    ],
    answer: 'a - b',
    tags: ['AC9M1M02'],
  },
  {
    id: 'maths.1.time.days-in-weeks',
    subject: 'maths',
    topic: 'time',
    level: '1',
    prompt: 'How many days are there in {n} weeks?',
    vars: [{ name: 'n', kind: 'int', min: '2', max: '6' }],
    answer: 'n * 7',
    hint: 'There are 7 days in one week.',
    tags: ['AC9M1M03'],
  },
  {
    id: 'maths.1.time.hours-in-days',
    subject: 'maths',
    topic: 'time',
    level: '1',
    prompt: 'How many hours are there in {n} days?',
    vars: [{ name: 'n', kind: 'int', min: '2', max: '4' }],
    answer: 'n * 24',
    hint: 'There are 24 hours in one day.',
    tags: ['AC9M1M03'],
  },
  {
    id: 'maths.1.shapes.corners',
    subject: 'maths',
    topic: 'shapes',
    level: '1',
    prompt: 'How many corners does {article} {shape} have?',
    vars: [
      {
        name: 'shape',
        kind: 'pick',
        from: ['triangle', 'square', 'rectangle', 'pentagon', 'hexagon', 'octagon'],
      },
      // "a octagon" otherwise.
      { name: 'article', kind: 'expr', expr: "shape == 'octagon' ? 'an' : 'a'" },
    ],
    answer:
      "shape == 'triangle' ? 3 : shape == 'square' ? 4 : shape == 'rectangle' ? 4 : shape == 'pentagon' ? 5 : shape == 'hexagon' ? 6 : 8",
    tags: ['AC9M1SP01'],
  },
  {
    id: 'maths.1.shapes.name-picture',
    subject: 'maths',
    topic: 'shapes',
    level: '1',
    prompt: 'What shape is this?',
    vars: [
      { name: 'n', kind: 'pick', from: [3, 4, 5, 6] },
      { name: 'tri', kind: 'pick', from: ['equilateral', 'isosceles', 'scalene'] },
      {
        name: 'drawn',
        kind: 'expr',
        expr: "n == 3 ? tri : n == 4 ? 'square' : n == 5 ? 'pentagon' : 'hexagon'",
      },
    ],
    answer: shapeName('n'),
    answerType: 'choice',
    // The other three shapes, stepped round the 3..6 cycle so they never repeat.
    choices: {
      count: 4,
      distractors: [
        shapeName('mod(n - 2, 4) + 3'),
        shapeName('mod(n - 1, 4) + 3'),
        shapeName('mod(n, 4) + 3'),
      ],
    },
    figure: { kind: 'polygon', shape: 'drawn' },
    tags: ['AC9M1SP01'],
  },
  {
    id: 'maths.1.shapes.corners-picture',
    subject: 'maths',
    topic: 'shapes',
    level: '1',
    prompt: 'How many corners does this shape have?',
    vars: [
      {
        name: 'shape',
        kind: 'pick',
        from: [
          'equilateral',
          'isosceles',
          'right-triangle',
          'square',
          'rectangle',
          'rhombus',
          'kite',
          'pentagon',
          'hexagon',
          'octagon',
        ],
      },
    ],
    answer: sideCount('shape'),
    hint: 'A corner is where two sides meet.',
    figure: { kind: 'polygon', shape: 'shape' },
    tags: ['AC9M1SP01'],
  },
  {
    id: 'maths.1.shapes.side-count-claim',
    subject: 'maths',
    topic: 'shapes',
    level: '1',
    prompt: 'True or false: this shape has {claim} sides.',
    vars: [
      {
        name: 'shape',
        kind: 'pick',
        from: [
          'equilateral',
          'scalene',
          'square',
          'rectangle',
          'trapezium',
          'kite',
          'pentagon',
          'hexagon',
        ],
      },
      { name: 'sides', kind: 'expr', expr: sideCount('shape') },
      // Right half the time, by construction. Drawn as a free number between 3
      // and 6 the claim came out true only a quarter of the time, because the
      // four-sided shapes outnumber the rest - and a child who answered "false"
      // to everything would have scored 75% on a topic they had learned nothing
      // about. The false case is a near miss rather than an obviously wrong
      // number, or the picture stops being read at all.
      { name: 'right', kind: 'pick', from: [1, 0] },
      { name: 'nudge', kind: 'pick', from: [1, -1] },
      {
        name: 'claim',
        kind: 'expr',
        // A triangle can only be missed upwards: "2 sides" is not a claim
        // anybody weighs up, and it would land back on the true case anyway.
        expr: 'right == 1 ? sides : sides + (sides == 3 ? 1 : nudge)',
      },
    ],
    answer: 'sides == claim',
    figure: { kind: 'polygon', shape: 'shape' },
    tags: ['AC9M1SP01'],
  },
  {
    id: 'maths.1.data.compare-tallies',
    subject: 'maths',
    topic: 'data',
    level: '1',
    prompt: 'A class tally shows {a} children chose cats and {b} chose dogs. How many more chose cats?',
    vars: [
      { name: 'a', kind: 'int', min: '6', max: '18' },
      { name: 'b', kind: 'int', min: '1', max: '5' },
    ],
    answer: 'a - b',
    tags: ['AC9M1ST02'],
  },
];
