import type { QuestionTemplate } from '@/lib/templates/types';
import { sideCount } from './helpers';

/** Year 2 - NSW Stage 1. */
export const year2: QuestionTemplate[] = [
  // ------------------------------------------------------------------
  // Year 2
  //
  // Numbers to 1000 and three-digit place value, halves, quarters and eighths
  // through repeated halving, addition and subtraction facts to 20, the twos
  // multiplication facts, money, additive patterns, calendars, clock times to
  // the quarter hour, and quarter and half turns.
  // ------------------------------------------------------------------
  {
    id: 'maths.2.counting-numbers.largest',
    subject: 'maths',
    topic: 'counting numbers',
    level: '2',
    prompt: 'Which of these is the largest: {a}, {b} or {c}?',
    vars: [
      { name: 'a', kind: 'int', min: '100', max: '999' },
      { name: 'b', kind: 'int', min: '100', max: '999' },
      { name: 'c', kind: 'int', min: '100', max: '999' },
    ],
    constraints: ['a != b', 'b != c', 'a != c'],
    answer: 'max(a, b, c)',
    hint: 'Compare the hundreds first.',
    tags: ['AC9M2N01'],
  },
  {
    id: 'maths.2.place-value.count-hundreds',
    subject: 'maths',
    topic: 'place value',
    level: '2',
    prompt: 'How many whole hundreds are there in {x}?',
    vars: [{ name: 'x', kind: 'int', min: '150', max: '999' }],
    answer: 'floor(x / 100)',
    tags: ['AC9M2N02'],
  },
  {
    id: 'maths.2.place-value.build',
    subject: 'maths',
    topic: 'place value',
    level: '2',
    prompt: 'What number is {h} hundreds, {t} tens and {o} ones?',
    vars: [
      { name: 'h', kind: 'int', min: '2', max: '9' },
      { name: 't', kind: 'int', min: '2', max: '9' },
      { name: 'o', kind: 'int', min: '2', max: '9' },
    ],
    answer: 'h * 100 + t * 10 + o',
    tags: ['AC9M2N02'],
  },
  {
    id: 'maths.2.place-value.zero-digit',
    subject: 'maths',
    topic: 'place value',
    level: '2',
    prompt: 'What number is {h} hundreds and {o} ones, with no tens?',
    vars: [
      { name: 'h', kind: 'int', min: '2', max: '9' },
      { name: 'o', kind: 'int', min: '2', max: '9' },
    ],
    answer: 'h * 100 + o',
    hint: 'A zero holds the tens place open.',
    tags: ['AC9M2N02'],
  },
  {
    id: 'maths.2.addition.two-digit',
    subject: 'maths',
    topic: 'addition',
    level: '2',
    prompt: 'What is {x} + {y}?',
    vars: [
      { name: 'x', kind: 'int', min: '10', max: '59' },
      { name: 'y', kind: 'int', min: '10', max: '39' },
    ],
    answer: 'x + y',
    hint: 'Add the tens, then add the ones.',
    tags: ['AC9M2N04'],
  },
  {
    id: 'maths.2.addition.missing-addend',
    subject: 'maths',
    topic: 'addition',
    level: '2',
    prompt: 'What goes in the box? {x} + ? = {total}',
    vars: [
      { name: 'x', kind: 'int', min: '2', max: '20' },
      { name: 'y', kind: 'int', min: '2', max: '20' },
      { name: 'total', kind: 'expr', expr: 'x + y' },
    ],
    answer: 'y',
    hint: 'How many more than {x} is {total}?',
    tags: ['AC9M2N04'],
  },
  {
    id: 'maths.2.addition.facts-to-twenty',
    subject: 'maths',
    topic: 'addition',
    level: '2',
    prompt: 'What is {x} + {y}?',
    vars: [
      { name: 'x', kind: 'int', min: '4', max: '16' },
      { name: 'y', kind: 'int', min: '4', max: '20 - x' },
    ],
    answer: 'x + y',
    tags: ['AC9M2A02'],
  },
  {
    id: 'maths.2.subtraction.two-digit',
    subject: 'maths',
    topic: 'subtraction',
    level: '2',
    prompt: 'What is {x} − {y}?',
    vars: [
      { name: 'x', kind: 'int', min: '20', max: '99' },
      { name: 'y', kind: 'int', min: '10', max: '49' },
    ],
    constraints: ['x > y'],
    answer: 'x - y',
    tags: ['AC9M2N04'],
  },
  {
    id: 'maths.2.subtraction.facts-to-twenty',
    subject: 'maths',
    topic: 'subtraction',
    level: '2',
    prompt: 'What is {total} − {x}?',
    vars: [
      { name: 'total', kind: 'int', min: '11', max: '20' },
      { name: 'x', kind: 'int', min: '2', max: '9' },
    ],
    answer: 'total - x',
    hint: 'If you know {x} + {total - x} = {total}, you know this one.',
    tags: ['AC9M2A02'],
  },
  {
    id: 'maths.2.addition-and-subtraction.mixed',
    subject: 'maths',
    topic: 'addition and subtraction',
    level: '2',
    prompt: 'What is {x} {op} {y}?',
    vars: [
      { name: 'x', kind: 'int', min: '10', max: '30' },
      { name: 'y', kind: 'int', min: '1', max: '9' },
      { name: 'op', kind: 'pick', from: ['+', '−'] },
    ],
    answer: "op == '+' ? x + y : x - y",
    tags: ['AC9M2N04'],
  },
  {
    id: 'maths.2.even-and-odd.next-odd',
    subject: 'maths',
    topic: 'even and odd',
    level: '2',
    prompt: '{x} is an odd number. What is the next odd number?',
    vars: [{ name: 'x', kind: 'int', min: '21', max: '97', step: 2 }],
    constraints: ['isOdd(x)'],
    answer: 'x + 2',
    tags: ['AC9M2A01'],
  },
  {
    id: 'maths.2.even-and-odd.previous-even',
    subject: 'maths',
    topic: 'even and odd',
    level: '2',
    prompt: 'What is the largest even number smaller than {x}?',
    vars: [{ name: 'x', kind: 'int', min: '21', max: '99' }],
    constraints: ['isOdd(x)'],
    answer: 'x - 1',
    tags: ['AC9M2A01'],
  },
  {
    id: 'maths.2.multiplication.doubles',
    subject: 'maths',
    topic: 'multiplication',
    level: '2',
    prompt: 'What is double {x}?',
    vars: [{ name: 'x', kind: 'int', min: '2', max: '20' }],
    answer: 'x * 2',
    hint: '{x} + {x}',
    tags: ['AC9M2A03'],
  },
  {
    id: 'maths.2.multiplication.twos',
    subject: 'maths',
    topic: 'multiplication',
    level: '2',
    prompt: 'What is {x} × 2?',
    vars: [{ name: 'x', kind: 'int', min: '2', max: '12' }],
    answer: 'x * 2',
    tags: ['AC9M2A03'],
  },
  {
    id: 'maths.2.multiplication.equal-groups',
    subject: 'maths',
    topic: 'multiplication',
    level: '2',
    prompt: 'There are {n} bags with {each} marbles in each bag. How many marbles altogether?',
    vars: [
      { name: 'n', kind: 'int', min: '2', max: '6' },
      { name: 'each', kind: 'pick', from: [2, 5, 10] },
    ],
    answer: 'n * each',
    hint: 'Skip count by {each}s, {n} times.',
    tags: ['AC9M2N05'],
  },
  {
    id: 'maths.2.division.halving',
    subject: 'maths',
    topic: 'division',
    level: '2',
    prompt: '{total} counters are shared equally between 2 children. How many does each child get?',
    vars: [{ name: 'each', kind: 'int', min: '3', max: '20' }, { name: 'total', kind: 'expr', expr: 'each * 2' }],
    answer: 'each',
    tags: ['AC9M2A03'],
  },
  {
    id: 'maths.2.division.by-twos',
    subject: 'maths',
    topic: 'division',
    level: '2',
    prompt: 'What is {total} ÷ 2?',
    vars: [{ name: 'half', kind: 'int', min: '3', max: '25' }, { name: 'total', kind: 'expr', expr: 'half * 2' }],
    answer: 'half',
    hint: 'Halving is the opposite of doubling.',
    tags: ['AC9M2A03'],
  },
  {
    id: 'maths.2.fractions.half-of',
    subject: 'maths',
    topic: 'fractions',
    level: '2',
    prompt: 'What is half of {x}?',
    vars: [{ name: 'half', kind: 'int', min: '2', max: '20' }, { name: 'x', kind: 'expr', expr: 'half * 2' }],
    answer: 'half',
    hint: 'Split {x} into 2 equal parts.',
    tags: ['AC9M2N03'],
  },
  {
    id: 'maths.2.fractions.quarter-of',
    subject: 'maths',
    topic: 'fractions',
    level: '2',
    prompt: 'What is one quarter of {x}?',
    vars: [{ name: 'quarter', kind: 'int', min: '2', max: '12' }, { name: 'x', kind: 'expr', expr: 'quarter * 4' }],
    answer: 'quarter',
    hint: 'Halve {x}, then halve it again.',
    tags: ['AC9M2N03'],
  },
  {
    id: 'maths.2.fractions.repeated-halving',
    subject: 'maths',
    topic: 'fractions',
    level: '2',
    prompt: 'Half of {x} is {x / 2}. What is half of {x / 2}?',
    vars: [{ name: 'quarter', kind: 'int', min: '2', max: '12' }, { name: 'x', kind: 'expr', expr: 'quarter * 4' }],
    answer: 'quarter',
    tags: ['AC9M2N03'],
  },
  {
    id: 'maths.2.fractions.parts-of-a-whole',
    subject: 'maths',
    topic: 'fractions',
    level: '2',
    prompt: 'How many {name} make one whole?',
    vars: [{ name: 'name', kind: 'pick', from: ['halves', 'quarters', 'eighths'] }],
    answer: "name == 'halves' ? 2 : name == 'quarters' ? 4 : 8",
    tags: ['AC9M2N03', 'AC9M2M02'],
  },
  {
    id: 'maths.2.number-patterns.additive',
    subject: 'maths',
    topic: 'number patterns',
    level: '2',
    prompt: 'What comes next? {a}, {a + d}, {a + 2 * d}, {a + 3 * d}, ?',
    vars: [
      { name: 'a', kind: 'int', min: '1', max: '20' },
      { name: 'd', kind: 'int', min: '3', max: '9' },
    ],
    answer: 'a + 4 * d',
    hint: 'The numbers go up by {d} each time.',
    tags: ['AC9M2A01'],
  },
  {
    id: 'maths.2.number-patterns.missing-element',
    subject: 'maths',
    topic: 'number patterns',
    level: '2',
    prompt: 'Fill in the gap: {a}, ?, {a + 2 * d}, {a + 3 * d}',
    vars: [
      { name: 'a', kind: 'int', min: '2', max: '30' },
      { name: 'd', kind: 'int', min: '2', max: '9' },
    ],
    answer: 'a + d',
    tags: ['AC9M2A01'],
  },
  {
    id: 'maths.2.number-patterns.decreasing',
    subject: 'maths',
    topic: 'number patterns',
    level: '2',
    prompt: 'What comes next? {a}, {a - d}, {a - 2 * d}, ?',
    vars: [
      { name: 'd', kind: 'int', min: '2', max: '9' },
      { name: 'a', kind: 'int', min: 'd * 4', max: 'd * 10' },
    ],
    answer: 'a - 3 * d',
    tags: ['AC9M2A01'],
  },
  {
    id: 'maths.2.money.coins-to-dollars',
    subject: 'maths',
    topic: 'money',
    level: '2',
    prompt: 'How many 50c coins make ${d}?',
    vars: [{ name: 'd', kind: 'int', min: '1', max: '6' }],
    answer: 'd * 2',
    hint: 'Two 50c coins make one dollar.',
    tags: ['AC9M2N06'],
  },
  {
    id: 'maths.2.money.total-cents',
    subject: 'maths',
    topic: 'money',
    level: '2',
    prompt: 'A pencil costs {a}c and a rubber costs {b}c. How much do they cost together, in cents?',
    vars: [
      { name: 'a', kind: 'int', min: '5', max: '95', step: 5 },
      { name: 'b', kind: 'int', min: '5', max: '95', step: 5 },
    ],
    answer: 'a + b',
    tags: ['AC9M2N06'],
  },
  {
    id: 'maths.2.time.half-hours',
    subject: 'maths',
    topic: 'time',
    level: '2',
    prompt: 'How many minutes are there in {n} half-hours?',
    vars: [{ name: 'n', kind: 'int', min: '2', max: '6' }],
    answer: 'n * 30',
    hint: 'Half an hour is 30 minutes.',
    tags: ['AC9M2M04'],
  },
  {
    id: 'maths.2.time.calendar-days',
    subject: 'maths',
    topic: 'time',
    level: '2',
    prompt: 'Today is the {d}th of the month. What date will it be in {k} days?',
    vars: [
      { name: 'd', kind: 'int', min: '1', max: '20' },
      { name: 'k', kind: 'int', min: '2', max: '7' },
    ],
    answer: 'd + k',
    tags: ['AC9M2M03'],
  },
  {
    id: 'maths.2.turns.quarter-turns',
    subject: 'maths',
    topic: 'turns',
    level: '2',
    prompt: 'How many quarter turns are there in {n} full turns?',
    vars: [{ name: 'n', kind: 'int', min: '1', max: '5' }],
    answer: 'n * 4',
    hint: 'One full turn is 4 quarter turns.',
    tags: ['AC9M2M05'],
  },
  {
    id: 'maths.2.shapes.sides',
    subject: 'maths',
    topic: 'shapes',
    level: '2',
    prompt: 'How many sides does {article} {shape} have?',
    vars: [
      {
        name: 'shape',
        kind: 'pick',
        from: ['triangle', 'quadrilateral', 'pentagon', 'hexagon', 'heptagon', 'octagon'],
      },
      { name: 'article', kind: 'expr', expr: "shape == 'octagon' ? 'an' : 'a'" },
    ],
    answer:
      "shape == 'triangle' ? 3 : shape == 'quadrilateral' ? 4 : shape == 'pentagon' ? 5 : shape == 'hexagon' ? 6 : shape == 'heptagon' ? 7 : 8",
    tags: ['AC9M2SP01'],
  },
  {
    id: 'maths.2.shapes.name-picture',
    subject: 'maths',
    topic: 'shapes',
    level: '2',
    // The four names a child has to count sides to tell apart - a pentagon and
    // a hexagon are not told apart at a glance the way a square and a triangle
    // are, which is the step up from Year 1.
    prompt: 'What shape is this?',
    vars: [
      { name: 'shape', kind: 'pick', from: ['pentagon', 'hexagon', 'heptagon', 'octagon'] },
    ],
    answer: 'shape',
    answerType: 'choice',
    choices: {
      count: 4,
      distractors: ["'pentagon'", "'hexagon'", "'heptagon'", "'octagon'"],
    },
    hint: 'Count the sides: 5 pentagon, 6 hexagon, 7 heptagon, 8 octagon.',
    figure: { kind: 'polygon', shape: 'shape' },
    tags: ['AC9M2SP01'],
  },
  {
    id: 'maths.2.shapes.sides-picture',
    subject: 'maths',
    topic: 'shapes',
    level: '2',
    prompt: 'How many sides does this shape have?',
    vars: [
      { name: 'shape', kind: 'pick', from: ['pentagon', 'hexagon', 'heptagon', 'octagon'] },
    ],
    answer: sideCount('shape'),
    figure: { kind: 'polygon', shape: 'shape' },
    tags: ['AC9M2SP01'],
  },
  {
    id: 'maths.2.shapes.more-sides-than',
    subject: 'maths',
    topic: 'shapes',
    level: '2',
    prompt: 'True or false: this shape has more than {n} sides.',
    vars: [
      {
        name: 'shape',
        kind: 'pick',
        from: [
          'scalene',
          'isosceles',
          'square',
          'trapezium',
          'parallelogram',
          'pentagon',
          'hexagon',
          'heptagon',
          'octagon',
        ],
      },
      { name: 'sides', kind: 'expr', expr: sideCount('shape') },
      { name: 'n', kind: 'int', min: '3', max: '7' },
    ],
    answer: 'sides > n',
    figure: { kind: 'polygon', shape: 'shape' },
    tags: ['AC9M2SP01'],
  },
];
