import type { QuestionTemplate } from '@/lib/templates/types';

/** Year 3 - NSW Stage 2. Which of Part A or B a concept sits in is a teacher's call, not the content's. */
export const year3: QuestionTemplate[] = [
  // ------------------------------------------------------------------
  // Year 3
  //
  // Numbers beyond 10 000, unit fractions and their multiples, three-digit
  // addition and subtraction, the 3, 4, 5 and 10 multiplication facts and the
  // related division facts, inverse operations, estimation, metric units,
  // time to the minute, right angles, money, and likelihood.
  // ------------------------------------------------------------------
  {
    id: 'maths.3.place-value.count-thousands',
    subject: 'maths',
    topic: 'place value',
    level: '3',
    prompt: 'How many whole thousands are there in {x}?',
    vars: [{ name: 'x', kind: 'int', min: '1200', max: '99999' }],
    answer: 'floor(x / 1000)',
    tags: ['AC9M3N01'],
  },
  {
    id: 'maths.3.place-value.digit-value',
    subject: 'maths',
    topic: 'place value',
    level: '3',
    prompt: 'In the number {x}, what is the value of the digit in the hundreds place?',
    vars: [{ name: 'x', kind: 'int', min: '1000', max: '9999' }],
    constraints: ['mod(floor(x / 100), 10) != 0'],
    answer: 'mod(floor(x / 100), 10) * 100',
    hint: 'A digit in the hundreds place is worth that many hundreds.',
    tags: ['AC9M3N01'],
  },
  {
    id: 'maths.3.counting-numbers.round-to-ten',
    subject: 'maths',
    topic: 'counting numbers',
    level: '3',
    prompt: 'Round {x} to the nearest 10.',
    vars: [{ name: 'x', kind: 'int', min: '21', max: '989' }],
    constraints: ['mod(x, 10) != 5', 'mod(x, 10) != 0'],
    answer: 'round(x / 10) * 10',
    tags: ['AC9M3N05'],
  },
  {
    id: 'maths.3.addition.three-digit',
    subject: 'maths',
    topic: 'addition',
    level: '3',
    prompt: 'What is {x} + {y}?',
    vars: [
      { name: 'x', kind: 'int', min: '100', max: '699' },
      { name: 'y', kind: 'int', min: '100', max: '299' },
    ],
    answer: 'x + y',
    hint: 'Add the hundreds, then the tens, then the ones.',
    tags: ['AC9M3N03'],
  },
  {
    id: 'maths.3.addition.regrouping',
    subject: 'maths',
    topic: 'addition',
    level: '3',
    prompt: 'What is {x} + {y}?',
    vars: [
      { name: 'x', kind: 'int', min: '145', max: '486' },
      { name: 'y', kind: 'int', min: '117', max: '298' },
    ],
    constraints: ['mod(x, 10) + mod(y, 10) > 10'],
    answer: 'x + y',
    hint: 'The ones make more than ten, so one ten is carried over.',
    tags: ['AC9M3N03'],
  },
  {
    id: 'maths.3.subtraction.three-digit',
    subject: 'maths',
    topic: 'subtraction',
    level: '3',
    prompt: 'What is {x} − {y}?',
    vars: [
      { name: 'x', kind: 'int', min: '300', max: '999' },
      { name: 'y', kind: 'int', min: '100', max: '299' },
    ],
    answer: 'x - y',
    tags: ['AC9M3N03'],
  },
  {
    id: 'maths.3.multiplication.tables',
    subject: 'maths',
    topic: 'multiplication',
    level: '3',
    prompt: 'What is {x} × {y}?',
    vars: [
      { name: 'x', kind: 'int', min: '2', max: '10' },
      { name: 'y', kind: 'int', min: '2', max: '10' },
    ],
    answer: 'x * y',
    hint: '{y} groups of {x}.',
    tags: ['AC9M3N04'],
  },
  {
    id: 'maths.3.multiplication.groups',
    subject: 'maths',
    topic: 'multiplication',
    level: '3',
    prompt: 'There are {x} boxes with {y} pencils in each. How many pencils altogether?',
    vars: [
      { name: 'x', kind: 'int', min: '2', max: '9' },
      { name: 'y', kind: 'int', min: '2', max: '9' },
    ],
    answer: 'x * y',
    tags: ['AC9M3N06'],
  },
  {
    id: 'maths.3.multiplication.known-facts',
    subject: 'maths',
    topic: 'multiplication',
    level: '3',
    prompt: 'What is {x} × {fact}?',
    vars: [
      { name: 'fact', kind: 'pick', from: [3, 4, 5, 10] },
      { name: 'x', kind: 'int', min: '2', max: '10' },
    ],
    answer: 'x * fact',
    tags: ['AC9M3A03'],
  },
  {
    id: 'maths.3.division.exact',
    subject: 'maths',
    topic: 'division',
    level: '3',
    prompt: 'What is {total} ÷ {y}?',
    vars: [
      { name: 'y', kind: 'int', min: '2', max: '10' },
      { name: 'x', kind: 'int', min: '2', max: '10' },
      { name: 'total', kind: 'expr', expr: 'x * y' },
    ],
    answer: 'x',
    hint: 'How many {y}s fit into {total}?',
    tags: ['AC9M3N04'],
  },
  {
    id: 'maths.3.division.sharing',
    subject: 'maths',
    topic: 'division',
    level: '3',
    prompt: '{total} sweets are shared equally between {y} children. How many does each child get?',
    vars: [
      { name: 'y', kind: 'int', min: '2', max: '6' },
      { name: 'x', kind: 'int', min: '2', max: '10' },
      { name: 'total', kind: 'expr', expr: 'x * y' },
    ],
    answer: 'x',
    tags: ['AC9M3N06'],
  },
  {
    id: 'maths.3.division.related-fact',
    subject: 'maths',
    topic: 'division',
    level: '3',
    prompt: 'You know {x} × {fact} = {x * fact}. What is {x * fact} ÷ {fact}?',
    vars: [
      { name: 'fact', kind: 'pick', from: [3, 4, 5, 10] },
      { name: 'x', kind: 'int', min: '2', max: '10' },
    ],
    answer: 'x',
    hint: 'Division undoes multiplication.',
    tags: ['AC9M3A03'],
  },
  {
    id: 'maths.3.fractions.unit-fraction-of',
    subject: 'maths',
    topic: 'fractions',
    level: '3',
    prompt: 'What is one {name} of {total}?',
    vars: [
      { name: 'd', kind: 'pick', from: [3, 4, 5, 10] },
      // Spelled out: "one 3th of 12" is not how anyone says it.
      {
        name: 'name',
        kind: 'expr',
        expr: "d == 3 ? 'third' : d == 4 ? 'quarter' : d == 5 ? 'fifth' : 'tenth'",
      },
      { name: 'part', kind: 'int', min: '2', max: '9' },
      { name: 'total', kind: 'expr', expr: 'd * part' },
    ],
    answer: 'part',
    hint: 'Split {total} into {d} equal parts.',
    tags: ['AC9M3N02'],
  },
  {
    id: 'maths.3.fractions.multiple-of-unit',
    subject: 'maths',
    topic: 'fractions',
    level: '3',
    prompt: 'What is {n} {plural} of {total}?',
    vars: [
      { name: 'd', kind: 'pick', from: [3, 4, 5, 10] },
      {
        name: 'name',
        kind: 'expr',
        expr: "d == 3 ? 'third' : d == 4 ? 'quarter' : d == 5 ? 'fifth' : 'tenth'",
      },
      {
        name: 'plural',
        kind: 'expr',
        expr: "d == 3 ? 'thirds' : d == 4 ? 'quarters' : d == 5 ? 'fifths' : 'tenths'",
      },
      { name: 'part', kind: 'int', min: '2', max: '8' },
      { name: 'total', kind: 'expr', expr: 'd * part' },
      { name: 'n', kind: 'int', min: '2', max: 'd - 1' },
    ],
    answer: 'n * part',
    hint: 'One {name} of {total} is {part}.',
    tags: ['AC9M3N02'],
  },
  {
    id: 'maths.3.fractions.complete-the-whole',
    subject: 'maths',
    topic: 'fractions',
    level: '3',
    prompt: 'You have {n} {plural} of a cake. How many more {plural} do you need to make a whole cake?',
    vars: [
      { name: 'd', kind: 'pick', from: [3, 4, 5, 10] },
      {
        name: 'plural',
        kind: 'expr',
        expr: "d == 3 ? 'thirds' : d == 4 ? 'quarters' : d == 5 ? 'fifths' : 'tenths'",
      },
      // From 2, so the prompt never reads "1 quarters".
      { name: 'n', kind: 'int', min: '2', max: 'd - 1' },
    ],
    answer: 'd - n',
    tags: ['AC9M3N02'],
  },
  {
    id: 'maths.3.algebra.unknown-value',
    subject: 'maths',
    topic: 'algebra',
    level: '3',
    prompt: 'What goes in the box? ? + {y} = {total}',
    vars: [
      { name: 'x', kind: 'int', min: '20', max: '180' },
      { name: 'y', kind: 'int', min: '10', max: '90' },
      { name: 'total', kind: 'expr', expr: 'x + y' },
    ],
    answer: 'x',
    hint: 'Take {y} away from {total}.',
    tags: ['AC9M3A01'],
  },
  {
    id: 'maths.3.algebra.inverse-operations',
    subject: 'maths',
    topic: 'algebra',
    level: '3',
    prompt: 'You know that {x} + {y} = {total}. What is {total} − {y}?',
    vars: [
      { name: 'x', kind: 'int', min: '15', max: '120' },
      { name: 'y', kind: 'int', min: '5', max: '80' },
      { name: 'total', kind: 'expr', expr: 'x + y' },
    ],
    answer: 'x',
    hint: 'Adding and subtracting undo each other.',
    tags: ['AC9M3A01'],
  },
  {
    id: 'maths.3.algebra.mental-strategy',
    subject: 'maths',
    topic: 'algebra',
    level: '3',
    prompt: 'You know {x} + {y} = {x + y}. What is {x * 10} + {y * 10}?',
    vars: [
      { name: 'x', kind: 'int', min: '2', max: '9' },
      { name: 'y', kind: 'int', min: '2', max: '9' },
    ],
    answer: '(x + y) * 10',
    hint: 'Ten times bigger in, ten times bigger out.',
    tags: ['AC9M3A02'],
  },
  {
    id: 'maths.3.time.minutes-in-hours',
    subject: 'maths',
    topic: 'time',
    level: '3',
    prompt: 'How many minutes are there in {n} hours?',
    vars: [{ name: 'n', kind: 'int', min: '2', max: '8' }],
    answer: 'n * 60',
    tags: ['AC9M3M03'],
  },
  {
    id: 'maths.3.time.seconds-in-minutes',
    subject: 'maths',
    topic: 'time',
    level: '3',
    prompt: 'How many seconds are there in {n} minutes?',
    vars: [{ name: 'n', kind: 'int', min: '2', max: '9' }],
    answer: 'n * 60',
    tags: ['AC9M3M03'],
  },
  {
    id: 'maths.3.time.until-the-hour',
    subject: 'maths',
    topic: 'time',
    level: '3',
    prompt: 'It is {m} minutes past {h} o’clock. How many minutes until {h + 1} o’clock?',
    vars: [
      { name: 'h', kind: 'int', min: '1', max: '11' },
      { name: 'm', kind: 'int', min: '5', max: '55', step: 5 },
    ],
    answer: '60 - m',
    tags: ['AC9M3M04'],
  },
  {
    id: 'maths.3.measurement.centimetres',
    subject: 'maths',
    topic: 'measurement',
    level: '3',
    prompt: 'How many centimetres are there in {n} metres?',
    vars: [{ name: 'n', kind: 'int', min: '2', max: '9' }],
    answer: 'n * 100',
    hint: 'One metre is 100 centimetres.',
    tags: ['AC9M3M02'],
  },
  {
    id: 'maths.3.measurement.grams',
    subject: 'maths',
    topic: 'measurement',
    level: '3',
    prompt: 'How many grams are there in {n} kilograms?',
    vars: [{ name: 'n', kind: 'int', min: '2', max: '9' }],
    answer: 'n * 1000',
    tags: ['AC9M3M02'],
  },
  {
    id: 'maths.3.measurement.choose-unit',
    subject: 'maths',
    topic: 'measurement',
    level: '3',
    prompt: 'Would you measure the {thing} in metres or in centimetres?',
    vars: [
      {
        name: 'thing',
        kind: 'pick',
        from: ['length of a classroom', 'height of a door', 'length of a pencil', 'width of a stamp'],
      },
    ],
    answer:
      "thing == 'length of a classroom' || thing == 'height of a door' ? 'metres' : 'centimetres'",
    answerType: 'choice',
    choices: { count: 2, distractors: ["'metres'", "'centimetres'"] },
    tags: ['AC9M3M01'],
  },
  {
    id: 'maths.3.money.change',
    subject: 'maths',
    topic: 'money',
    level: '3',
    prompt: 'A sticker costs {c}c. You pay with a $2 coin. How much change do you get, in cents?',
    vars: [{ name: 'c', kind: 'int', min: '5', max: '195', step: 5 }],
    answer: '200 - c',
    hint: 'A $2 coin is 200 cents.',
    tags: ['AC9M3M06'],
  },
  {
    id: 'maths.3.money.cents-in-dollars',
    subject: 'maths',
    topic: 'money',
    level: '3',
    prompt: 'How many cents are there in ${d}?',
    vars: [{ name: 'd', kind: 'int', min: '2', max: '9' }],
    answer: 'd * 100',
    tags: ['AC9M3M06'],
  },
  {
    id: 'maths.3.angles.right-angles-in-a-turn',
    subject: 'maths',
    topic: 'angles',
    level: '3',
    prompt: 'How many right angles are there in a {turn} turn?',
    vars: [{ name: 'turn', kind: 'pick', from: ['half', 'three-quarter', 'full'] }],
    answer: "turn == 'half' ? 2 : turn == 'three-quarter' ? 3 : 4",
    hint: 'A quarter turn is one right angle.',
    tags: ['AC9M3M05'],
  },
  // The first two angle questions that show the angle. Neither pins a rotation
  // or an arm length, so the same angle arrives pointing anywhere and drawn
  // with a long arm and a short one - a child who reads a longer pair of arms
  // as a bigger angle is making the mistake this content description names.
  {
    id: 'maths.3.angles.against-a-right-angle',
    subject: 'maths',
    topic: 'angles',
    level: '3',
    prompt: 'Is this angle bigger or smaller than a right angle?',
    vars: [{ name: 'd', kind: 'int', min: '20', max: '160', step: 5 }],
    // Kept well clear of 90 on either side: an angle five degrees off a right
    // angle is not a child failing to compare, it is a picture with no
    // answerable difference in it.
    constraints: ['abs(d - 90) >= 25'],
    answer: "d > 90 ? 'bigger' : 'smaller'",
    answerType: 'choice',
    choices: { count: 2, distractors: ["'bigger'", "'smaller'"] },
    hint: 'A right angle is the square corner of a page.',
    figure: { kind: 'angle', degrees: 'd' },
    tags: ['AC9M3M05'],
  },
  {
    id: 'maths.3.angles.is-a-right-angle',
    subject: 'maths',
    topic: 'angles',
    level: '3',
    prompt: 'True or false: this is a right angle.',
    vars: [
      { name: 'square', kind: 'pick', from: [1, 0] },
      { name: 'off', kind: 'int', min: '25', max: '70', step: 5 },
      { name: 'side', kind: 'pick', from: [1, -1] },
      { name: 'd', kind: 'expr', expr: 'square == 1 ? 90 : 90 + side * off' },
    ],
    answer: 'square == 1',
    hint: 'A right angle is a quarter turn.',
    figure: { kind: 'angle', degrees: 'd' },
    tags: ['AC9M3M05'],
  },
  {
    id: 'maths.3.chance.more-likely',
    subject: 'maths',
    topic: 'chance',
    level: '3',
    prompt:
      'A bag holds {r} red counters and {b} blue counters. True or false: you are more likely to pull out a red one.',
    // From 2, so the prompt never reads "1 blue counters".
    vars: [
      { name: 'r', kind: 'int', min: '2', max: '12' },
      { name: 'b', kind: 'int', min: '2', max: '12' },
    ],
    constraints: ['r != b'],
    answer: 'r > b',
    tags: ['AC9M3P01'],
  },
  {
    id: 'maths.3.chance.which-colour',
    subject: 'maths',
    topic: 'chance',
    level: '3',
    prompt:
      'A bag holds {r} red counters and {b} blue counters. Which colour are you more likely to pull out?',
    vars: [
      { name: 'r', kind: 'int', min: '2', max: '15' },
      { name: 'b', kind: 'int', min: '2', max: '15' },
    ],
    constraints: ['r != b'],
    answer: "r > b ? 'red' : 'blue'",
    answerType: 'choice',
    choices: { count: 2, distractors: ["'red'", "'blue'"] },
    tags: ['AC9M3P01'],
  },
  {
    id: 'maths.3.data.survey-total',
    subject: 'maths',
    topic: 'data',
    level: '3',
    prompt:
      'In a survey, {a} children chose apples, {b} chose bananas and {c} chose cherries. How many children were surveyed?',
    vars: [
      { name: 'a', kind: 'int', min: '3', max: '25' },
      { name: 'b', kind: 'int', min: '3', max: '25' },
      { name: 'c', kind: 'int', min: '3', max: '25' },
    ],
    answer: 'a + b + c',
    tags: ['AC9M3ST01'],
  },
];
