import type { QuestionTemplate } from '@/lib/templates/types';

/** Year 4 - NSW Stage 2. Which of Part A or B a concept sits in is a teacher's call, not the content's. */
export const year4: QuestionTemplate[] = [
  // ------------------------------------------------------------------
  // Year 4
  //
  // Tenths and hundredths as decimals, the properties of odd and even numbers,
  // equivalent fractions and mixed numerals, multiplying and dividing by
  // powers of 10, all multiplication facts to 10 × 10, rounding, perimeter and
  // area, am and pm, angle names, and lines of symmetry.
  //
  // Decimal answers start here, where decimals enter the curriculum.
  // ------------------------------------------------------------------
  {
    id: 'maths.4.decimals.tenths',
    subject: 'maths',
    topic: 'decimals',
    level: '4',
    prompt: 'Write {n} tenths as a decimal.',
    vars: [{ name: 'n', kind: 'int', min: '1', max: '9' }],
    answer: 'n / 10',
    // Tapped, not typed: the number pad has no decimal point.
    answerType: 'choice',
    choices: { count: 4, distractors: ['n / 100', 'n', '(n + 1) / 10'] },
    hint: 'Tenths go in the first place after the decimal point.',
    tags: ['AC9M4N01'],
  },
  {
    id: 'maths.4.decimals.hundredths',
    subject: 'maths',
    topic: 'decimals',
    level: '4',
    prompt: 'Write {n} hundredths as a decimal.',
    vars: [{ name: 'n', kind: 'int', min: '11', max: '99' }],
    constraints: ['mod(n, 10) != 0'],
    answer: 'n / 100',
    answerType: 'choice',
    choices: { count: 4, distractors: ['n / 10', 'n', '(n + 1) / 100'] },
    tags: ['AC9M4N01'],
  },
  {
    id: 'maths.4.decimals.larger',
    subject: 'maths',
    topic: 'decimals',
    level: '4',
    prompt: 'Which is larger, {a} or {b}?',
    vars: [
      { name: 'a', kind: 'number', min: '0.1', max: '9.9', decimals: 1 },
      { name: 'b', kind: 'number', min: '0.1', max: '9.9', decimals: 1 },
    ],
    constraints: ['a != b'],
    answer: 'max(a, b)',
    answerType: 'choice',
    choices: { count: 2, distractors: ['min(a, b)'] },
    hint: 'Compare the whole numbers first, then the tenths.',
    tags: ['AC9M4N01'],
  },
  {
    id: 'maths.4.decimals.add-tenths',
    subject: 'maths',
    topic: 'decimals',
    level: '4',
    // Built from whole tenths so the arithmetic stays exact and the options read
    // cleanly - floating point noise in a distractor gives the answer away.
    prompt: 'What is {a} + {b}?',
    vars: [
      { name: 'na', kind: 'int', min: '11', max: '99' },
      { name: 'nb', kind: 'int', min: '11', max: '99' },
      { name: 'a', kind: 'expr', expr: 'na / 10' },
      { name: 'b', kind: 'expr', expr: 'nb / 10' },
    ],
    answer: '(na + nb) / 10',
    answerType: 'choice',
    choices: {
      count: 4,
      distractors: ['(na + nb + 1) / 10', '(na + nb - 1) / 10', '(na + nb + 10) / 10'],
    },
    hint: 'Add the whole numbers, then add the tenths.',
    tags: ['AC9M4N01'],
  },
  {
    id: 'maths.4.decimals.unit-fraction',
    subject: 'maths',
    topic: 'decimals',
    level: '4',
    prompt: 'Write 1/{d} as a decimal.',
    vars: [{ name: 'd', kind: 'pick', from: [2, 4, 5, 10] }],
    answer: '1 / d',
    answerType: 'choice',
    choices: { count: 4, distractors: ['d / 10', '(10 + d) / 100', '(100 - d) / 100'] },
    tags: ['AC9M4N03'],
  },
  {
    id: 'maths.4.even-and-odd.is-odd',
    subject: 'maths',
    topic: 'even and odd',
    level: '4',
    prompt: 'True or false: {x} is an odd number.',
    vars: [{ name: 'x', kind: 'int', min: '10', max: '199' }],
    answer: 'isOdd(x)',
    tags: ['AC9M4N02'],
  },
  {
    id: 'maths.4.even-and-odd.sum-parity',
    subject: 'maths',
    topic: 'even and odd',
    level: '4',
    prompt: 'True or false: {x} + {y} gives an even answer.',
    vars: [
      { name: 'x', kind: 'int', min: '2', max: '60' },
      { name: 'y', kind: 'int', min: '2', max: '60' },
    ],
    answer: 'isEven(x + y)',
    hint: 'Two odds make an even; an odd and an even make an odd.',
    tags: ['AC9M4N02'],
  },
  {
    id: 'maths.4.even-and-odd.product-parity',
    subject: 'maths',
    topic: 'even and odd',
    level: '4',
    prompt: 'True or false: {x} × {y} gives an odd answer.',
    vars: [
      { name: 'x', kind: 'int', min: '2', max: '20' },
      { name: 'y', kind: 'int', min: '2', max: '20' },
    ],
    answer: 'isOdd(x * y)',
    hint: 'One even number anywhere in a product makes the answer even.',
    tags: ['AC9M4N02'],
  },
  {
    id: 'maths.4.fractions.equivalent',
    subject: 'maths',
    topic: 'fractions',
    level: '4',
    prompt: 'Complete the equivalent fraction: {a}/{d} = ?/{d * k}',
    vars: [
      { name: 'd', kind: 'int', min: '2', max: '6' },
      { name: 'a', kind: 'int', min: '1', max: 'd - 1' },
      { name: 'k', kind: 'int', min: '2', max: '4' },
    ],
    answer: 'a * k',
    hint: 'The bottom was multiplied by {k}, so the top is too.',
    tags: ['AC9M4N03'],
  },
  {
    id: 'maths.4.fractions.of-a-quantity',
    subject: 'maths',
    topic: 'fractions',
    level: '4',
    prompt: 'What is {n}/{d} of {total}?',
    vars: [
      { name: 'd', kind: 'pick', from: [3, 4, 5, 8, 10] },
      { name: 'part', kind: 'int', min: '2', max: '9' },
      { name: 'total', kind: 'expr', expr: 'd * part' },
      { name: 'n', kind: 'int', min: '2', max: 'd - 1' },
    ],
    answer: 'n * part',
    tags: ['AC9M4N03'],
  },
  {
    id: 'maths.4.fractions.count-in-wholes',
    subject: 'maths',
    topic: 'fractions',
    level: '4',
    prompt: 'How many {d == 2 ? \'halves\' : d == 3 ? \'thirds\' : d == 4 ? \'quarters\' : d == 5 ? \'fifths\' : \'tenths\'} are there in {n} wholes?',
    vars: [
      { name: 'd', kind: 'pick', from: [2, 3, 4, 5, 10] },
      { name: 'n', kind: 'int', min: '2', max: '6' },
    ],
    answer: 'd * n',
    tags: ['AC9M4N04'],
  },
  {
    id: 'maths.4.fractions.mixed-numeral',
    subject: 'maths',
    topic: 'fractions',
    level: '4',
    prompt: 'How many quarters are there in {n} and three quarters?',
    vars: [{ name: 'n', kind: 'int', min: '1', max: '8' }],
    answer: 'n * 4 + 3',
    hint: 'Each whole is 4 quarters.',
    tags: ['AC9M4N04'],
  },
  {
    id: 'maths.4.multiplication.by-powers-of-ten',
    subject: 'maths',
    topic: 'multiplication',
    level: '4',
    prompt: 'What is {x} × {p}?',
    vars: [
      { name: 'x', kind: 'int', min: '2', max: '99' },
      { name: 'p', kind: 'pick', from: [10, 100, 1000] },
    ],
    answer: 'x * p',
    hint: 'Every digit shifts up to the next place value.',
    tags: ['AC9M4N05'],
  },
  {
    id: 'maths.4.multiplication.facts',
    subject: 'maths',
    topic: 'multiplication',
    level: '4',
    prompt: 'What is {x} × {y}?',
    vars: [
      { name: 'x', kind: 'int', min: '6', max: '10' },
      { name: 'y', kind: 'int', min: '6', max: '10' },
    ],
    answer: 'x * y',
    tags: ['AC9M4A02'],
  },
  {
    id: 'maths.4.multiplication.two-digit',
    subject: 'maths',
    topic: 'multiplication',
    level: '4',
    prompt: 'What is {x} × {y}?',
    vars: [
      { name: 'x', kind: 'int', min: '11', max: '49' },
      { name: 'y', kind: 'int', min: '3', max: '9' },
    ],
    answer: 'x * y',
    hint: 'Split {x} into tens and ones, multiply each, then add.',
    tags: ['AC9M4N06'],
  },
  {
    id: 'maths.4.division.by-powers-of-ten',
    subject: 'maths',
    topic: 'division',
    level: '4',
    prompt: 'What is {total} ÷ {p}?',
    vars: [
      { name: 'p', kind: 'pick', from: [10, 100] },
      { name: 'x', kind: 'int', min: '2', max: '99' },
      { name: 'total', kind: 'expr', expr: 'x * p' },
    ],
    answer: 'x',
    tags: ['AC9M4N05'],
  },
  {
    id: 'maths.4.division.facts',
    subject: 'maths',
    topic: 'division',
    level: '4',
    prompt: 'What is {total} ÷ {y}?',
    vars: [
      { name: 'y', kind: 'int', min: '6', max: '10' },
      { name: 'x', kind: 'int', min: '6', max: '10' },
      { name: 'total', kind: 'expr', expr: 'x * y' },
    ],
    answer: 'x',
    tags: ['AC9M4A02'],
  },
  {
    id: 'maths.4.estimation.round-to-hundred',
    subject: 'maths',
    topic: 'estimation',
    level: '4',
    prompt: 'Round {x} to the nearest 100.',
    vars: [{ name: 'x', kind: 'int', min: '210', max: '9890' }],
    constraints: ['mod(x, 100) != 50', 'mod(x, 100) != 0'],
    answer: 'round(x / 100) * 100',
    tags: ['AC9M4N07'],
  },
  {
    id: 'maths.4.estimation.rounded-sum',
    subject: 'maths',
    topic: 'estimation',
    level: '4',
    prompt: 'Estimate {a} + {b} by rounding each number to the nearest 10 first.',
    vars: [
      { name: 'a', kind: 'int', min: '21', max: '289' },
      { name: 'b', kind: 'int', min: '21', max: '289' },
    ],
    constraints: ['mod(a, 10) != 5', 'mod(b, 10) != 5'],
    answer: 'round(a / 10) * 10 + round(b / 10) * 10',
    tags: ['AC9M4N07'],
  },
  {
    id: 'maths.4.algebra.unknown-value',
    subject: 'maths',
    topic: 'algebra',
    level: '4',
    prompt: 'What goes in the box? {total} − ? = {x}',
    vars: [
      { name: 'x', kind: 'int', min: '30', max: '400' },
      { name: 'y', kind: 'int', min: '20', max: '300' },
      { name: 'total', kind: 'expr', expr: 'x + y' },
    ],
    answer: 'y',
    tags: ['AC9M4A01'],
  },
  {
    id: 'maths.4.number-patterns.nth-term',
    subject: 'maths',
    topic: 'number patterns',
    level: '4',
    prompt: 'The rule is: add {d}. Starting at {a}, what is the 5th number in the pattern?',
    vars: [
      { name: 'a', kind: 'int', min: '2', max: '40' },
      { name: 'd', kind: 'int', min: '3', max: '12' },
    ],
    answer: 'a + 4 * d',
    hint: '{a} is the 1st number, so add {d} four more times.',
    tags: ['AC9M4N09'],
  },
  {
    id: 'maths.4.perimeter-and-area.rectangle-perimeter',
    subject: 'maths',
    topic: 'perimeter and area',
    level: '4',
    prompt: 'A rectangle is {l} cm long and {w} cm wide. What is its perimeter, in centimetres?',
    vars: [
      { name: 'l', kind: 'int', min: '3', max: '20' },
      { name: 'w', kind: 'int', min: '2', max: '15' },
    ],
    answer: '2 * (l + w)',
    hint: 'Add up all four sides.',
    tags: ['AC9M4M02'],
  },
  {
    id: 'maths.4.perimeter-and-area.rectangle-area',
    subject: 'maths',
    topic: 'perimeter and area',
    level: '4',
    prompt:
      'A rectangle is {l} squares long and {w} squares wide. How many squares cover it altogether?',
    vars: [
      { name: 'l', kind: 'int', min: '3', max: '12' },
      { name: 'w', kind: 'int', min: '2', max: '9' },
    ],
    answer: 'l * w',
    tags: ['AC9M4M02'],
  },
  {
    id: 'maths.4.time.am-or-pm',
    subject: 'maths',
    topic: 'time',
    level: '4',
    prompt: 'A film starts at {h} o’clock in the {part}. Is that am or pm?',
    vars: [
      { name: 'h', kind: 'int', min: '1', max: '11' },
      { name: 'part', kind: 'pick', from: ['morning', 'afternoon', 'evening'] },
    ],
    answer: "part == 'morning' ? 'am' : 'pm'",
    answerType: 'choice',
    choices: { count: 2, distractors: ["'am'", "'pm'"] },
    hint: 'am runs from midnight to midday.',
    tags: ['AC9M4M03'],
  },
  {
    id: 'maths.4.time.convert-minutes',
    subject: 'maths',
    topic: 'time',
    level: '4',
    prompt: 'How many minutes are there in {h} hours and {m} minutes?',
    vars: [
      { name: 'h', kind: 'int', min: '2', max: '6' },
      { name: 'm', kind: 'int', min: '5', max: '55', step: 5 },
    ],
    answer: 'h * 60 + m',
    tags: ['AC9M4M03'],
  },
  {
    id: 'maths.4.angles.larger-angle',
    subject: 'maths',
    topic: 'angles',
    level: '4',
    prompt: 'Which is the larger angle, {a} or {b}?',
    vars: [
      { name: 'a', kind: 'pick', from: ['acute', 'right', 'obtuse', 'straight'] },
      { name: 'b', kind: 'pick', from: ['acute', 'right', 'obtuse', 'straight'] },
      {
        name: 'ra',
        kind: 'expr',
        expr: "a == 'acute' ? 1 : a == 'right' ? 2 : a == 'obtuse' ? 3 : 4",
      },
      {
        name: 'rb',
        kind: 'expr',
        expr: "b == 'acute' ? 1 : b == 'right' ? 2 : b == 'obtuse' ? 3 : 4",
      },
    ],
    constraints: ['ra != rb'],
    answer: 'ra > rb ? a : b',
    answerType: 'choice',
    choices: { count: 2, distractors: ['ra > rb ? b : a'] },
    hint: 'Smallest to largest: acute, right, obtuse, straight.',
    tags: ['AC9M4M04'],
  },
  {
    id: 'maths.4.angles.is-acute',
    subject: 'maths',
    topic: 'angles',
    level: '4',
    prompt: "True or false: an angle of {n} quarter turn{n == 1 ? '' : 's'} is larger than a right angle.",
    vars: [{ name: 'n', kind: 'int', min: '1', max: '4' }],
    answer: 'n > 1',
    hint: 'One quarter turn is exactly a right angle.',
    tags: ['AC9M4M04'],
  },
  {
    id: 'maths.4.angles.name-picture',
    subject: 'maths',
    topic: 'angles',
    level: '4',
    prompt: 'What kind of angle is this?',
    vars: [
      { name: 'kind', kind: 'pick', from: ['acute', 'right', 'obtuse', 'straight'] },
      // Both bands are held clear of the two angles that are also *options*
      // here: 25 degrees off the right angle and 20 off the straight one, the
      // same clearances the two-way questions at Year 3 and Year 4 take. This
      // is the hardest of the angle questions - four names, no right-angle
      // tick to give the square corner away, and a rotation that leaves
      // nothing upright to judge against - so it is the one that can least
      // afford an acute angle ten degrees off square.
      { name: 'small', kind: 'int', min: '15', max: '65', step: 5 },
      { name: 'large', kind: 'int', min: '115', max: '160', step: 5 },
      {
        name: 'd',
        kind: 'expr',
        expr: "kind == 'acute' ? small : kind == 'right' ? 90 : kind == 'obtuse' ? large : 180",
      },
    ],
    answer: 'kind',
    answerType: 'choice',
    choices: {
      count: 4,
      distractors: ["'acute'", "'right'", "'obtuse'", "'straight'"],
    },
    hint: 'Smallest to largest: acute, right, obtuse, straight.',
    figure: { kind: 'angle', degrees: 'd' },
    tags: ['AC9M4M04'],
  },
  {
    id: 'maths.4.angles.is-obtuse',
    subject: 'maths',
    topic: 'angles',
    level: '4',
    prompt: 'True or false: this angle is obtuse.',
    vars: [{ name: 'd', kind: 'int', min: '15', max: '170', step: 5 }],
    constraints: ['abs(d - 90) >= 20'],
    answer: 'd > 90',
    hint: 'An obtuse angle is bigger than a right angle and smaller than a straight one.',
    figure: { kind: 'angle', degrees: 'd' },
    tags: ['AC9M4M04'],
  },
  {
    id: 'maths.4.symmetry.lines',
    subject: 'maths',
    topic: 'symmetry',
    level: '4',
    prompt: 'How many lines of symmetry does {article} {shape} have?',
    vars: [
      {
        name: 'shape',
        kind: 'pick',
        from: ['square', 'rectangle', 'equilateral triangle', 'regular pentagon', 'regular hexagon'],
      },
      { name: 'article', kind: 'expr', expr: "shape == 'equilateral triangle' ? 'an' : 'a'" },
    ],
    answer:
      "shape == 'square' ? 4 : shape == 'rectangle' ? 2 : shape == 'equilateral triangle' ? 3 : shape == 'regular pentagon' ? 5 : 6",
    hint: 'A regular shape has as many lines of symmetry as it has sides.',
    tags: ['AC9M4SP03'],
  },
  {
    id: 'maths.4.symmetry.dashed-line',
    subject: 'maths',
    topic: 'symmetry',
    level: '4',
    prompt: 'True or false: the dashed line is a line of symmetry.',
    vars: [
      { name: 'real', kind: 'pick', from: [1, 0] },
      // Every shape here has at least one axis, so the true case is always
      // drawable, and none is rounder than a hexagon, so the false case's line
      // is far enough off a real axis to be seen - a heptagon's wrong line
      // lands eleven degrees out, which is a picture with no answer in it.
      {
        name: 'shape',
        kind: 'pick',
        from: [
          'equilateral',
          'isosceles',
          'trapezium',
          'kite',
          'square',
          'rectangle',
          'rhombus',
          'pentagon',
          'hexagon',
        ],
      },
    ],
    answer: 'real == 1',
    hint: 'Fold along the line: would the two halves land on top of each other?',
    figure: { kind: 'polygon', shape: 'shape', mirror: 'real == 1' },
    tags: ['AC9M4SP03'],
  },
  {
    id: 'maths.4.symmetry.count-picture',
    subject: 'maths',
    topic: 'symmetry',
    level: '4',
    prompt: 'How many lines of symmetry does this shape have?',
    vars: [
      {
        name: 'shape',
        kind: 'pick',
        from: [
          'scalene',
          'right-triangle',
          'parallelogram',
          'isosceles',
          'trapezium',
          'kite',
          'rectangle',
          'rhombus',
          'equilateral',
          'square',
          'pentagon',
          'hexagon',
        ],
      },
    ],
    // None, one, two, then the regular shapes, which have one per side. Zero is
    // an answer the number pad can give, and a shape with no symmetry at all is
    // the case the worded version of this question never gets to ask.
    answer:
      "shape == 'scalene' || shape == 'right-triangle' || shape == 'parallelogram' ? 0 : " +
      "shape == 'isosceles' || shape == 'trapezium' || shape == 'kite' ? 1 : " +
      "shape == 'rectangle' || shape == 'rhombus' ? 2 : shape == 'equilateral' ? 3 : " +
      "shape == 'square' ? 4 : shape == 'pentagon' ? 5 : 6",
    hint: 'A regular shape has one for every side, and some shapes have none at all.',
    figure: { kind: 'polygon', shape: 'shape' },
    tags: ['AC9M4SP03'],
  },
  {
    id: 'maths.4.data.many-to-one',
    subject: 'maths',
    topic: 'data',
    level: '4',
    prompt: 'On a pictograph each picture stands for {k} children. How many children do {n} pictures show?',
    vars: [
      { name: 'k', kind: 'pick', from: [2, 5, 10] },
      { name: 'n', kind: 'int', min: '3', max: '12' },
    ],
    answer: 'k * n',
    tags: ['AC9M4ST01'],
  },
  {
    id: 'maths.4.chance.least-likely',
    subject: 'maths',
    topic: 'chance',
    level: '4',
    prompt:
      'A bag holds {r} red, {b} blue and {g} green marbles. Which colour are you least likely to pull out?',
    vars: [
      { name: 'r', kind: 'int', min: '2', max: '20' },
      { name: 'b', kind: 'int', min: '2', max: '20' },
      { name: 'g', kind: 'int', min: '2', max: '20' },
    ],
    constraints: ['r != b', 'b != g', 'r != g'],
    answer: "r < b && r < g ? 'red' : b < g ? 'blue' : 'green'",
    answerType: 'choice',
    choices: { count: 3, distractors: ["'red'", "'blue'", "'green'"] },
    tags: ['AC9M4P01'],
  },
];
